### ISSUE TITLE
this is my first issue. Pls comment this

### ISSUE THREAD

**Issue by Anna-Khvatova** [Khvatov-Alexey/test#2]
**Hiho!** 
Please, add to project `console.log('hihi!')`
### THANKS

**Comment by Anna-Khvatova** [comment]
> **Hiho!** Please, add to project `console.log('hihi!')`

Great suggerestion! It'll be in the next version.

**Comment by Anna-Khvatova** [comment]
> Great suggerestion! It'll be in the next version.

It should have been my words))

**Comment by Khvatov-Alexey** [comment]
> Please, add to project console.log('hihi!')

Great suggestion! This'll be added in the next version.

**Comment by Khvatov-Alexey** [comment]
> ### THANKS

Thank you for your contribution!
